name = "rizhi-sync"
main = "worker.js"
compatibility_date = "2026-07-02"

kv_namespaces = [
  { binding = "RIZHI_STORE", id = "77f104d2864e48d5b30e2d8036e6b528" }
]

[vars]
ALLOWED_ORIGINS = "https://tangwenzhenyx-maker.github.io,http://127.0.0.1:8782,http://localhost:8782"
